### ISSUE TITLE
Comparison to new "profles" feature

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/global-config#15]
Been using this for ages. Now there's that new ["Profiles" feature](https://code.visualstudio.com/updates/v1_75#_profiles) (which doesn't seem documented :-( so I'm not sure of all the details).

Do you know whether it makes this extension obsolete, or if it serves a different purpose?

**Comment by Gruntfuggly** [comment]
I haven't look into profiles yet - I wrote this extension to just set up new workspaces easily, and it still does that job for me. 😄
