### ISSUE TITLE
Help required in configuring the extension.

### ISSUE THREAD

**Issue by kalpaj12** [Gruntfuggly/global-config#4]
I have a .vscode folder with a few shell files that run when executing a .cpp task. This .vscode folder is currently on my desktop. When I try creating a new .cpp file (not on desktop), It opts me to create a new task. I've made changes to **global-config.folder** by changing its fields to /home/kalpaj/Desktop
/.vscode. 

Can I know what steps am I missing, and if possible a step by step guide on how to configure this extension properly?
Thanks in advance!

**Comment by Gruntfuggly** [comment]
Hi - I'm not sure what is causing the problem you are seeing? The extension just copies files from the `global-config.folder` into the `.vscode` folder in your workspace.

I.e.

I have a folder `~/dev-support/vscode/standard/linux` which contains:
  `c_cpp_properties.json`
  `launch.json`
  `settings.json`
  `tasks.json`

If I then have a workspace such as:

`~/workspace/asldev/project`

When I run the global config `copy` command, it copies the above files into:

`~/workspace/asldev/project/.vscode`

(it creates soft links for the `tasks.json` file as I want it to be the same in all my workspaces).

Could you list the steps you are doing, so I can try the same thing?

**Comment by kalpaj12** [comment]
**When I run the global config `copy` command, it copies the above files into...**
I was missing this step. Everything works fine now! Thanks for the extension.
P.s. I could suggest a readme update with explicit step by step instructions. It was no where mentioned to run the copy command, and creation of symlink(vs code settings to be copied over different workspaces) just confused me.

Thanks again!

**Comment by Gruntfuggly** [comment]
I'm glad you've got it working. :grin:

In the first paragraph it says _"so this extension simply adds a command Copy Global Config to copy them into the local .vscode folder from a shared location."_

Some steps might be useful though...

**Comment by kalpaj12** [comment]
Thanks for the help!

It does say that, but since I'm new to vs code, I thought the functionality that was begin provided was copy. For me, it wasn't clear enough, until you specifically mentioned, I had to run the `copy` command  :blush:

**Comment by kalpaj12** [comment]
Close issue?

**Comment by Gruntfuggly** [comment]
I'll leave it open until I update the README.md in case I forget. :grin:

**Comment by kalpaj12** [comment]
Oh, cool! Thanks alot though!(For the extension and the help)

**Comment by kalpaj12** [comment]
Hi again,
Is there a provision to copy folders present inside .vscode? Right now, this extension ignores them.

**Comment by Gruntfuggly** [comment]
Yes, I deliberately ignored folders as it didn't seem necessary. I can add it fairly easily (I think). Out of interest, what is your use case for folders?

**Comment by kalpaj12** [comment]
I am into competitive coding, I have few files that belong to a specific folder and I'd prefer having them in those folders. So, for now, I need to manually copy them to my workspace folder;-;

**Comment by kalpaj12** [comment]
I was just wondering whether the implementation of providing copy function for sub-folders inside .vscode was an option.

P.s. sent a pull request to modify the readme. Please have a look
Thanks though! :)

**Comment by Gruntfuggly** [comment]
I've uploaded a new version which will copy folders too.
I've updated the README based on your changes, but I couldn't accept it as it was because it removed the details about symlinks.

**Comment by kalpaj12** [comment]
Thanks!!!

**Comment by andrewufrank** [comment]
I would appreciate a more prominent 

How to Use
Install "global config" 
issue ctrl-P, type "copy" and select "copy Global Config"

I would be  helpful an example how the "global-config.links" should look in the settings.

Otherwise - thank you for a valuable tool!
