### ISSUE TITLE
Add ability to choose config(s) to copy

### ISSUE THREAD

**Issue by aliusmiles** [Gruntfuggly/global-config#7]
Really useful plugin, many thanks!

Ability to choose global config to copy would be super useful when working on different projects. Something like:
```
$HOME/.vscode-global-configs
├── python-3.7
│   ├── settings.json
│   └── tasks.json
├── terraform-11
│   ├── settings.json
│   └── tasks.json
└── terraform-12
    ├── settings.json
    └── tasks.json
```
set list of config folders in settings and then 'Copy Global Config' command would ask which one to copy to local .vscode.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version.

**Comment by aliusmiles** [comment]
Awesome! works like a charm with following config:

```
    "global-config.folder": "~/.vscode/global-configs/",
    "global-config.folders": [
        "terraform-11",
        "terraform-12",
    ],
```
Maybe update Readme.md as well? Or I can create PR later if you busy at the moment.

And many thanks for such a prompt reply and fix!

**Comment by Gruntfuggly** [comment]
It should work automatically - you don't need the config for `global-config.folders` - looks like I committed that by accident.

**Comment by aliusmiles** [comment]
Confirmed, worked automatically. Thanks again!
